### ISSUE TITLE
API from reticulum server get bad gateway 502 if accessed from Hubs admin

### ISSUE THREAD

**Issue by albirrkarim** [mozilla/reticulum#551]
Refering to this https://github.com/mozilla/hubs/issues/4970#issue-1087523703

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/29292018/153163485-a78d533c-5aa9-4ab2-941d-2d17063138ea.png">

[https://hubs.local:4000/api/postgrest/pending_scenes?limit=10&offset=0&order=id.desc](https://hubs.local:4000/api/postgrest/pending_scenes?limit=10&offset=0&order=id.desc)

if i acess from browser tab it will get some result

<img width="453" alt="image" src="https://user-images.githubusercontent.com/29292018/153163614-887999c9-3987-4157-8777-1614e4236746.png">

Log on reticulum server

[info] Sent 502 in 14ms

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/29292018/153163801-3244d281-0d39-4b65-bd70-3af1f042010a.png">

So where is the problem here?

No error mesages ?

The hubs admin or reticulum server?

**Comment by albirrkarim** [comment]
solved with this https://github.com/mozilla/Spoke/issues/1215#issuecomment-1032429599

**Comment by albirrkarim** [comment]
Im doing this https://github.com/mozilla/Spoke/issues/1215#issuecomment-1032429599 

The error `TLS :server: In state :certify received CLIENT ALERT: Fatal - Bad Certificate` is clear

But still getting 502 Server communication error

**Comment by ninjavaz** [comment]
What was the solution?

**Comment by albirrkarim** [comment]
No solution for that. Maybe its for hubs cloud. I dont know.

I dont need that to be solve, because i can run the entire system now

https://github.com/albirrkarim/mozilla-hubs-installation-detailed

**Comment by ninjavaz** [comment]
Thank you for answer. Do you know how to properly connect PostgREST to hubs admin? I spent a lot of time solving it, but still don't have any solution. Specifically, the error is - JWSError JWSInvalidSignature.

**Comment by albirrkarim** [comment]
https://github.com/mozilla/hubs-ops/wiki/Running-PostgREST-locally

**Comment by ninjavaz** [comment]
I had installed postgREST in exactly the same way as in this link and still facing problem with redirecting to login panel after click any option in Admin Panel menu. Maybe do you know something else? I would be very gratefull! Thanks in advance.

**Comment by albirrkarim** [comment]
You run in local or self-hosted server .?

hubs cloud or like in my turorial?

**Comment by ninjavaz** [comment]
Self hosted server, like in your tutorial

**Comment by albirrkarim** [comment]
Have you done this [step](https://github.com/albirrkarim/mozilla-hubs-installation-detailed/blob/main/VPS_FOR_HUBS.md#additional-modification-for-hubs-admin) ?

**Comment by ninjavaz** [comment]
Yes, I have commented line with pipe_through, then run postgREST service, created jwk based on Ret.PermsToken and other stuff.
My reticulum-conf.json:
```
db-uri = "postgres://postgres:postgres@localhost:5432/ret_dev"
db-schema = "ret0_admin"
db-anon-role = "postgres"
jwt-secret = "<path>/reticulum-jwk.json"
jwt-aud = "ret_perms"
role-claim-key = ".postgrest_role"
```
Do you have any idea?

**Comment by albirrkarim** [comment]
there are many possibilities. 

there are two way running hubs admin:
1. serve as live webpack server -> npm run prod
2. serve as static file -> run run build


if you try the number 1 with pm2 then its works. use the number 1. but the number 1 is taking more RAM.

if you can serve with number 2. it will less RAM usage.


Tips Debugging: 

**Both number 1 and 2 try on local first.**

for number 2 you can just install nginx then serve it on port 8989 (hubs admin port)

To avoid redirect (WHILE DEBUGING) just modify the code of hubs admin.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/29292018/191135953-1db4cb1e-90cc-47dc-911a-0ddced7066b0.png">

you can just find the redirect direction url in vscode then comment it.

then you can see the network tab and the browser console. see what's going on.

**Comment by ninjavaz** [comment]
I come back to this issue and I face with error: 
"JWSError JWSInvalidSignature" as response for request:
<hubs_vps>/api/postgrest/featured_scene_listings?limit=10&offset=0&order=order.asc
It is definitely problem with postgrest. Maybe do you know solution for this kind of problem?

**Comment by ninjavaz** [comment]
@albirrkarim Could you take a look at my previous comment?

**Comment by ninjavaz** [comment]
Problem fixed with adding "@" in reticulum.conf, which is configuration file of postgREST
e.g.:
jwt-secret="@/apps/polyhubs/reticulum/reticulum-jwk.json"

As I realised, the @ sign was crucial here.

**Comment by bryanenders** [comment]
I’m glad you figured it out. For future reference, see [Hubs Compose](https://github.com/mozilla/hubs-compose/blob/main/files/dev-reticulum.conf).
